server.modules = (
    "mod_access",
    "mod_fastcgi"
)

server.document-root        = "/var/www/html/"
server.port                 = 1337
server.username             = "www-data"
server.groupname            = "www-data"
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"

# not really needed but was useful for debugging
# server.http-parseopts       = ( "url-ctrls-reject" => "disable","url-path-2f-decode" => "disable" )

# Serve /static/* directly as static files
$HTTP["url"] =~ "^/static/" {
    fastcgi.server = ()
}

# FastCGI configuration
fastcgi.server  = (
    "/" => (
        "neon" => (
            "socket" => "/tmp/neon/neon.sock",
            "check-local" => "disable",
            "docroot" => "/",
            "max-procs" => 1,
            "bin-path" => "/neon",
        )
    )
)
